secrets:
  redisSecretRef: op://ci/patchmon-redis
  postgresSecretRef: op://ci/patchmon-postgres
  oidcSecretRef: op://ci/patchmon-oidc
  patchmonSecretRef: op://ci/patchmon

ingress:
  clusterIssuer: ci
  domain: patchmon.ci.local
