apiVersion: v2
name: apache-tika
description: A Helm chart to deploy Apache Tika on Kubernetes
icon: https://www.apache.org/logos/res/tika/default.png

type: application

version: 8.0.0+up3.3.1.0.full
appVersion: "3.3.1.0-full"
