apiVersion: v2
name: rallly
description: A Helm chart to deploy Rallly on Kubernetes
icon: https://raw.githubusercontent.com/lukevella/rallly/main/apps/landing/public/apple-touch-icon.png

type: application

version: 8.1.3+up4.15.0
appVersion: "4.15.0"

maintainers:
  - name: jklein