apiVersion: v2
name: voucher-vault
description: A Helm chart to deploy VoucherVault on Kubernetes
icon: https://raw.githubusercontent.com/l4rm4nd/VoucherVault/main/myapp/static/assets/img/logo.png

type: application

version: 6.1.1+up1.30.2
appVersion: "1.30.2"

maintainers:
  - name: jklein