apiVersion: v2
name: satisfactory
description: A Helm chart to deploy a Satisfactory Gameserver on Kubernetes
icon: https://raw.githubusercontent.com/wolveix/satisfactory-server/main/.github/logo.png
type: application
version: 7.0.1+upv1.9.10
appVersion: "v1.9.10"
maintainers:
  - name: jklein