apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-service
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.xxx.securityContext.pod | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
          image: "registry/image:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- range $value := .Values.xxx.env }}
            {{- if $value.value }}
            - name: {{ $value.name }}
              value: {{ tpl $value.value $ }}
            {{- else if $value.valueFrom }}
            {{- if $value.valueFrom.secretKeyRef }}
            - name: {{ $value.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ tpl $value.valueFrom.secretKeyRef.name $ }}
                  key: {{ tpl $value.valueFrom.secretKeyRef.key $ }}
            {{- else if $value.valueFrom.configMapKeyRef }}
            - name: {{ $value.name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ tpl $value.valueFrom.configMapKeyRef.name $ }}
                  key: {{ tpl $value.valueFrom.configMapKeyRef.key $ }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            {{- toYaml .Values.xxx.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.xxx.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.xxx.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.xxx.startupProbe | nindent 12 }}
          resources:
            {{- include "xxx.resources" .Values.xxx.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.xxx.securityContext.container | nindent 12 }}
      restartPolicy: Always
