apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-core-config
data:
  config: |-
    http: !include http-config.yaml

  http-config: |-
    {{ toYaml .Values.homeassistant.config.httpConfig | indent 2 }}
