apiVersion: v2
name: cyberchef
description: A Helm chart to deploy Cyberchef on Kubernetes
icon: https://raw.githubusercontent.com/gchq/CyberChef/master/src/web/static/images/cyberchef-128x128.png

type: application

version: 8.0.0+up11.4.0
appVersion: "11.4.0"

maintainers:
  - name: jklein