apiVersion: v2
name: rss-bridge
description: A Helm chart to deploy RSS-Bridge on Kubernetes
icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/master/static/logo_300px.png

type: application

version: 1.0.1+up2025.08.05
appVersion: "2025-08-05"

maintainers:
  - name: jklein
