apiVersion: v2
name: gotenberg
description: A Helm chart to deploy Gotenberg on Kubernetes
icon: https://gotenberg.dev/img/logo.png

type: application

version: 5.1.0+up8.36.0
appVersion: "8.36.0"

maintainers:
  - name: jklein