apiVersion: v2
name: paperless-ngx
description: A Helm chart to deploy Paperless-NGX on Kubernetes
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/dev/src-ui/src/apple-touch-icon.png

type: application

version: 12.1.1+up3.1.0

appVersion: 3.1.0

maintainers:
  - name: jklein