apiVersion: v2
name: xxx
description: A Helm chart to deploy xxx on Kubernetes
icon: https://helm.sh/img/helm.svg

type: application

version: 4.1.0+upxxx
appVersion: "xxx"

maintainers:
  - name: jklein