apiVersion: v2
name: minecraft-router
description: A Helm chart for deploying a itzg/mc-router
icon: https://avatars.githubusercontent.com/u/988985

type: application

version: 4.1.1+up1.46.5
appVersion: "1.46.5"

maintainers:
  - name: jklein
