apiVersion: v2
name: minecraft-router
description: A Helm chart for deploying a itzg/mc-router
icon: https://avatars.githubusercontent.com/u/988985

type: application

version: 1.0.0+up1.25.1
appVersion: "1.25.1"

maintainers:
  - name: jklein
