apiVersion: v2
name: minecraft-router
description: A Helm chart for deploying a itzg/mc-router
icon: https://avatars.githubusercontent.com/u/988985

type: application

version: 4.0.0+up1.46.4
appVersion: "1.46.4"

maintainers:
  - name: jklein
