apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-database-secret
spec:
  itemPath: {{ required "You must provide a databaseSecret Reference" .Values.secrets.databaseSecretRef }}
