apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-sfs
  ports:
    - port: {{ .Values.server.voicePort }}
      name: voice-port
      targetPort: voice-port
      protocol: UDP
      nodePort: {{ .Values.server.voicePort }}
    - port: {{ .Values.server.fileTransferPort }}
      name: file-transfer
      targetPort: file-transfer
      protocol: TCP
      nodePort: {{ .Values.server.fileTransferPort }}
  type: NodePort
