apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  custom-routing-config.json: |
    {
      "mappings": {
    {{- $length := len .Values.mappings }}
    {{- $indexLength := sub $length 1 }}
    {{- range $index, $value := .Values.mappings }}
        "{{ $value.domain }}": "{{ $value.internalUrl }}:25565"{{ if lt $index $indexLength }},{{ end }}
    {{- end }}
      }
    }
