apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"