{{- if .Values.smbConnection.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-consume-cronjob
spec:
  schedule: {{ .Values.smbConnection.cronJob }}
  {{- if .Values.scaleDown }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          securityContext:
            {{- toYaml .Values.smbConnection.cron.securityContext.pod | nindent 12 }}
          containers:
            - name: paperless-consume-cronjob
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              securityContext:
                {{- toYaml .Values.smbConnection.cron.securityContext.container | nindent 16 }}
              command:
                - /bin/sh
                - -c
                - if [ "$(find /mnt/smb -maxdepth 1 -name "*.pdf" -print)" ]; then mv /mnt/smb/*.pdf /mnt/consume; fi
              volumeMounts:
                - name: smb-share
                  mountPath: "/mnt/smb"
                  readOnly: false
                - name: consume-folder
                  mountPath: "/mnt/consume"
                  readOnly: false
              resources:
                {{- include "paperless-ngx.resources" .Values.smbConnection.cron.resources | nindent 16 }}
          restartPolicy: Never
          volumes:
            - name: smb-share
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-{{ .Chart.Name }}-smb-volume-claim
            - name: consume-folder
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-{{ .Chart.Name }}-consume-volume-claim
{{- end }}