apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis-secret
spec:
  itemPath: {{ required "A secret-reference for the Redis-Secret must be provided" .Values.secrets.redisSecretRef }}
