apiVersion: v2
name: freesailarr
description: A Helm chart to deploy a Wireguard-tunneled media automation stack (gluetun, qbittorrent, the *arrs, seerr) on Kubernetes
icon: https://raw.githubusercontent.com/qdm12/gluetun/master/doc/logo_256.png

type: application

version: 1.0.0+upv3.41.1
appVersion: "v3.41.1"

maintainers:
  - name: jklein
