apiVersion: v2
name: patchmon
description: A Helm chart to deploy Patchmon on Kubernetes
icon: https://raw.githubusercontent.com/PatchMon/PatchMon/main/frontend/public/assets/logo_square_default.svg

type: application

version: 5.1.0+up2.1.3
appVersion: "2.1.3"

maintainers:
  - name: jklein
