apiVersion: v2
name: matrix-synapse
description: A Helm chart to deploy a Matrix Synapse server on Kubernetes
icon: https://raw.githubusercontent.com/element-hq/synapse/develop/docs/favicon.png
type: application
version: 7.0.1+upv1.159.0
appVersion: "v1.159.0"
maintainers:
  - name: jklein