apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis-secret
spec:
  itemPath: {{ required "A Secret-Reference for the config must be provided" .Values.secrets.redisSecretRef }}
