name: Publish Matrix Synapse Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - matrix-synapse/**
jobs:
  publish-matrix-synapse:
    name: Publish Matrix Synapse Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'matrix-synapse'
    secrets: inherit
