name: Publish Homeassistant Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - homeassistant/**
jobs:
  publish-homeassistant:
    name: Publish Homeassistant Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'homeassistant'
    secrets: inherit
