name: Publish Satisfactory Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - satisfactory/**
jobs:
  publish-satisfactory:
    name: Publish Satisfactory Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'satisfactory'
    secrets: inherit
