name: Publish Patchmon Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - patchmon/**
jobs:
  publish-patchmon:
    name: Publish Patchmon Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'patchmon'
    secrets: inherit
