name: Publish Rallly Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - rallly/**
jobs:
  publish-rallly:
    name: Publish Rallly Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'rallly'
    secrets: inherit
