name: Publish Apache Tika Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apache-tika/**
jobs:
  publish-apache-tika:
    name: Publish Apache Tika Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'apache-tika'
    secrets: inherit
