name: Publish Cyberchef Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cyberchef/**
jobs:
  publish-cyberchef:
    name: Publish Cyberchef Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'cyberchef'
    secrets: inherit
