name: Publish Outline Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - outline/**
jobs:
  publish-outline:
    name: Publish Outline Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'outline'
    secrets: inherit
