name: Publish Gotenberg Helm Chart
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - gotenberg/**
jobs:
  publish-gotenberg:
    name: Publish Gotenberg Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'gotenberg'
    secrets: inherit
