apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-config
data:
  init.sh: |
    echo "downloading serverpack"
    wget -O /modpacks/serverpack.zip {{ .Values.curseforgeServerpack.downloadUrl }}
    SERVERPACK_DIR="{{ .Values.curseforgeServerpack.workingDirectory }}"
    BACKUP_DIR="/data/serverpack-backup"

    if [ -d "$SERVERPACK_DIR" ]; then
      echo "found installed server. Migrating..."
      if [ -d "$BACKUP_DIR" ]; then
        echo "clearing old Backup"
        rm -rf $BACKUP_DIR
      fi

      echo "backing up old server-files"
      cp -r $SERVERPACK_DIR $BACKUP_DIR

      rm -rf $SERVERPACK_DIR
      mkdir $SERVERPACK_DIR

      echo "extracting new server-files"
      tar -xvf /modpacks/serverpack.zip -C $SERVERPACK_DIR

      echo "copying old configuration-data"
      cp -r $BACKUP_DIR/world $SERVERPACK_DIR/world
      cp $BACKUP_DIR/banned-ips.json $SERVERPACK_DIR/banned-ips.json
      cp $BACKUP_DIR/banned-players.json $SERVERPACK_DIR/banned-players.json
      cp $BACKUP_DIR/ops.json $SERVERPACK_DIR/ops.json
      cp $BACKUP_DIR/whitelist.json $SERVERPACK_DIR/whitelist.json

      echo "change owner of files"
      chown -R 1000:1000 $SERVERPACK_DIR

      echo "successfully migrated server"

      # echo "deleting serverpack.zip"
      # rm /modpacks/serverpack.zip
    fi
